language: php

php:
  - 7.1
  - 7.2
  - 7.3
install:
  - composer install --no-interaction
script: php vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
